# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mburger/git/extrap-annaeling

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mburger/git/extrap-annaeling

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mburger/git/extrap-annaeling/CMakeFiles /home/mburger/git/extrap-annaeling/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mburger/git/extrap-annaeling/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SimAnMoLibraryTester

# Build rule for target.
SimAnMoLibraryTester: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimAnMoLibraryTester
.PHONY : SimAnMoLibraryTester

# fast build rule for target.
SimAnMoLibraryTester/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimAnMoLibraryTester.dir/build.make CMakeFiles/SimAnMoLibraryTester.dir/build
.PHONY : SimAnMoLibraryTester/fast

#=============================================================================
# Target rules for targets named SimAnMo

# Build rule for target.
SimAnMo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimAnMo
.PHONY : SimAnMo

# fast build rule for target.
SimAnMo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimAnMo.dir/build.make CMakeFiles/SimAnMo.dir/build
.PHONY : SimAnMo/fast

#=============================================================================
# Target rules for targets named SimAnMoLib

# Build rule for target.
SimAnMoLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimAnMoLib
.PHONY : SimAnMoLib

# fast build rule for target.
SimAnMoLib/fast:
	$(MAKE) $(MAKESILENT) -f SimulatedAnnealingExtraP/CMakeFiles/SimAnMoLib.dir/build.make SimulatedAnnealingExtraP/CMakeFiles/SimAnMoLib.dir/build
.PHONY : SimAnMoLib/fast

#=============================================================================
# Target rules for targets named AlgLib

# Build rule for target.
AlgLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AlgLib
.PHONY : AlgLib

# fast build rule for target.
AlgLib/fast:
	$(MAKE) $(MAKESILENT) -f SimulatedAnnealingExtraP/alglib/CMakeFiles/AlgLib.dir/build.make SimulatedAnnealingExtraP/alglib/CMakeFiles/AlgLib.dir/build
.PHONY : AlgLib/fast

SimAnMoDriver/main.o: SimAnMoDriver/main.cpp.o

.PHONY : SimAnMoDriver/main.o

# target to build an object file
SimAnMoDriver/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimAnMo.dir/build.make CMakeFiles/SimAnMo.dir/SimAnMoDriver/main.cpp.o
.PHONY : SimAnMoDriver/main.cpp.o

SimAnMoDriver/main.i: SimAnMoDriver/main.cpp.i

.PHONY : SimAnMoDriver/main.i

# target to preprocess a source file
SimAnMoDriver/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimAnMo.dir/build.make CMakeFiles/SimAnMo.dir/SimAnMoDriver/main.cpp.i
.PHONY : SimAnMoDriver/main.cpp.i

SimAnMoDriver/main.s: SimAnMoDriver/main.cpp.s

.PHONY : SimAnMoDriver/main.s

# target to generate assembly for a file
SimAnMoDriver/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimAnMo.dir/build.make CMakeFiles/SimAnMo.dir/SimAnMoDriver/main.cpp.s
.PHONY : SimAnMoDriver/main.cpp.s

SimAnMoTest/main.o: SimAnMoTest/main.cpp.o

.PHONY : SimAnMoTest/main.o

# target to build an object file
SimAnMoTest/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimAnMoLibraryTester.dir/build.make CMakeFiles/SimAnMoLibraryTester.dir/SimAnMoTest/main.cpp.o
.PHONY : SimAnMoTest/main.cpp.o

SimAnMoTest/main.i: SimAnMoTest/main.cpp.i

.PHONY : SimAnMoTest/main.i

# target to preprocess a source file
SimAnMoTest/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimAnMoLibraryTester.dir/build.make CMakeFiles/SimAnMoLibraryTester.dir/SimAnMoTest/main.cpp.i
.PHONY : SimAnMoTest/main.cpp.i

SimAnMoTest/main.s: SimAnMoTest/main.cpp.s

.PHONY : SimAnMoTest/main.s

# target to generate assembly for a file
SimAnMoTest/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimAnMoLibraryTester.dir/build.make CMakeFiles/SimAnMoLibraryTester.dir/SimAnMoTest/main.cpp.s
.PHONY : SimAnMoTest/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AlgLib"
	@echo "... SimAnMo"
	@echo "... SimAnMoLib"
	@echo "... SimAnMoLibraryTester"
	@echo "... SimAnMoDriver/main.o"
	@echo "... SimAnMoDriver/main.i"
	@echo "... SimAnMoDriver/main.s"
	@echo "... SimAnMoTest/main.o"
	@echo "... SimAnMoTest/main.i"
	@echo "... SimAnMoTest/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

